# Generated by Django 5.0 on 2024-01-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
