# Generated by Django 5.0 on 2024-01-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_feature",
            field=models.BooleanField(default=False, verbose_name="Главная"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
    ]
