# Generated by Django 5.0 on 2024-01-15 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_productimage_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="store.product",
                verbose_name="Продукт",
            ),
        ),
    ]
