# Generated by Django 5.0 on 2024-01-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Юзернейм'),
        ),
    ]
