# Generated by Django 5.0 on 2024-01-15 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_customer_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
    ]
